apiVersion: v1
kind: Service
metadata:
  name: yolo-client-servive
  namespace: default
     labels:
       run: yolo-client-servive
spec:
  selector:
    app: yolo_client
  ports:
    - protocol: TCP
      port: 3000
      name: client-port
  type: NodePort


      