version: "3.3"

services:
  backend:
    container_name: backend_container
    image: mchawi/node:yolo_backend
    ports:
      - 5000:5000
    depends_on: 
      - db
    volumes:
      - ./backend:/app
    environment:
      PORT: 5000

    
  db:
    container_name: database_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 9q1M1fhl4K!KwTAJ
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_vol:/data/db
      
  client:
    container_name: client_container
    image: mchawi/node:yolo_client
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    volumes:
      - ./client:/app



volumes:
  mongodb_vol: