apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo_backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: yolo-backend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo_backend
    spec:
      containers:
      - name: yolo-backend
        image: mchawi/node:yolo_backend
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - mountPath: "/tmp"
            name: yolo_backend 
        env:
          - name: MONGODB_URI
            valueFrom: 
              secretKeyRef:
                name: backend-secrets
                key: MONGODB_URI
      volumes:
      - name: yolo_backend
        persistentVolumeClaim:
          claimName: yolo-pvc-file-system

         