kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yolo-pvc-file-system
spec:
  volumeMode: Filesystem  
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: yolo-storageclass