apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9kZ2ljaGFiYTo5OXhLemtFODBkcmE0V04wQG15Y2x1c3Rlci5xdXh1Z200Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  