apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-servive
  namespace: default
     labels:
       run: yolo-backend-servive
spec:
  selector:
    app: yolo_backend
  ports:
    - protocol: TCP
      port: 5000
      name: backend-port
  type: NodePort


      